/*
 * File: app/view/ThesaurusPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HadocApp.view.ThesaurusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.thesaurusPanel',

    title: 'Vocabulaire : Thésaurus désignation',
    closable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Vocabulaire : scientifique (ID)',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Enregistrer'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Créer version'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Titre'
                        },
                        {
                            xtype: 'combobox',
                            value: 'all',
                            fieldLabel: 'Langues',
                            allowBlank: false,
                            editable: false,
                            displayField: 'langlabel',
                            forceSelection: true,
                            multiSelect: true,
                            //store: 'LanguagesStore',
                            valueField: 'langid'
                        },
                        {
                            xtype: 'propertygrid',
                            width: 503,
                            title: 'Metadonnées',
                            forceFit: false,
                            source: {
                                'Property 1': 'String',
                                'Property 2': true,
                                'Property 3': '2013-01-09T13:49:41',
                                'Property 4': 123
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            title: 'Historique de version',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Version'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Boolean'
                                }
                            ],
                            viewConfig: {

                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});